name: start-carrot-test-from-pr-comment
on: 
    issue_comment:
        types: [created]
jobs:
    publish-test:
        runs-on: ubuntu-18.04
        steps:
            # To use this repository's private action,
            # you must check out the repository
            - name: Checkout
              uses: actions/checkout@v2
            - name: Parse comment
              uses: ./.github/workflows/parse-comment-for-carrot-command/
              with:
                comment-body: ${{ github.event.comment.body }}
                software-name: gatk
                github-token: ${{ secrets.GITHUB_TOKEN }}
                topic-name: ${{ secrets.CARROT_TOPIC_NAME }}
                sa-key: ${{ secrets.CARROT_SA_KEY }}
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
